###
GET   http://localhost:3000/todos
content-type: application/json

###
POST  http://localhost:3000/todos
content-type: application/json

{
  "text": "eat breakfast 3"
}

###
PATCH  http://localhost:3000/todos/0.02677147224755161
content-type: application/json

{
  "text": "eat breakfast 1"
}

###
DELETE  http://localhost:3000/todos/0.02677147224755161
content-type: application/json

